import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

import Map from "../../components/Map";

import client from "@/apollo";
import { GET_LOCATIONS } from "@/apollo/gql";
import { GetStaticProps } from "next";
import LocationCard from "@/components/LocationCard";
import useWindowDimensions from "@/hooks/useWindowDimensions";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ allLocations }) {
  const winDim = useWindowDimensions();
  console.log(allLocations, "current");
  if (winDim.width < 600)
    return (
      <>
        <Head>
          <title>Find a Loo - Current Location</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link
            href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500&family=Philosopher&display=swap"
            rel="stylesheet"
          />
        </Head>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flex: 1,
            width: "100%",
          }}
        >
          <div style={{ display: "flex", height: "30vh", minHeight: "180px" }}>
            <Map />
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              flex: 1,
              justifyContent: "center",
              alignItems: "center",
              padding: 14,
              height: "100%",
              minHeight: "200px",
            }}
          >
            <div
              style={{
                backgroundColor: "#6A77FD",
                display: "flex",
                flex: "1 1 auto",
                flexDirection: "column",
                alignItems: "center",
                width: "100%",
                maxWidth: 600,
                borderRadius: 25,
                padding: "4px 8px 10px 8px",
                position: "relative",
                overflow: "hidden",
                overflowY: "scroll",
                height: "0",
              }}
            >
              <h3
                style={{
                  fontFamily: "Cinzel, sans-serif",
                  fontSize: 24,
                  fontWeight: "lighter",
                  margin: 10,
                  display: "flex",
                }}
              >
                Free Loo Near You
              </h3>
              <div
                style={{
                  display: "flex",
                  flexDirection: "column",
                  flex: 1,
                  gap: 10,
                  width: "100%",
                }}
              >
                {allLocations.map((location) => (
                  <LocationCard location={location} />
                ))}
              </div>
            </div>
          </div>
        </div>
      </>
    );
  return (
    <>
      <Head>
        <title>Find a Loo - Current Location</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500&family=Philosopher&display=swap"
          rel="stylesheet"
        />
      </Head>

      <div
        style={{
          display: "flex",
          flexDirection: "column",
          flex: 1,
          width: "100%",
        }}
      >
        <div style={{ display: "flex", height: "30vh", minHeight: "180px" }}>
          <Map />
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            flex: 1,
            justifyContent: "center",
            alignItems: "center",
            padding: 30,
            height: "100%",
            minHeight: "300px",
          }}
        >
          <div
            style={{
              backgroundColor: "#6A77FD",
              paddingBottom: 20,
              display: "flex",
              flex: "1 1 auto",
              flexDirection: "column",
              alignItems: "center",
              width: "100%",
              maxWidth: 600,
              borderRadius: 25,
              padding: "10px 20px 30px 20px",
              position: "relative",
              overflow: "hidden",
              overflowY: "scroll",
              height: "0",
            }}
          >
            <h3
              style={{
                fontFamily: "Cinzel, sans-serif",
                fontSize: 34,
                fontWeight: "lighter",
                margin: 30,
                display: "flex",
              }}
            >
              Free Loo Near You
            </h3>
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                flex: 1,
                gap: 10,
                width: "100%",
              }}
            >
              {allLocations.map((location) => (
                <LocationCard location={location} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export const getStaticProps: GetStaticProps = async ({ params }) => {
  const results = await client.query({
    query: GET_LOCATIONS,
  });
  if (!results) {
    return { notFound: true };
  }

  return {
    props: {
      allLocations: results.data.allLocation,
    },
    revalidate: 600,
  };
};
