import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Find a Loo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500&family=Philosopher&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* font-family: 'Mulish', sans-serif; font-family: 'Philosopher', sans-serif; */}
      <main
        style={{
          display: "flex",
          width: "100%",
          minHeight: "100vh",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Image
          alt="travel"
          src="/images/blackspace_back.webp"
          fill={true}
          quality={100}
          style={{ zIndex: -11, objectFit: "cover" }}
        />
        <section
          style={{
            display: "flex",
            flexDirection: "column",
            margin: 20,
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <h1
            style={{
              fontSize: 100,
              fontFamily: "Philosopher, sans-serif",
              textAlign: "center",
            }}
          >
            Find a Loo
          </h1>
          <div
            style={{
              maxWidth: 760,
              margin: "40px 0",
              display: "flex",
              flexDirection: "column",
            }}
          >
            <h3
              style={{
                fontSize: 18,
                textAlign: "center",
                fontFamily: "Mulish, sans-serif",
                fontWeight: "400",
              }}
            >
              Life's been pretty shitty lately. But finding a restroom shouldn't
              be shitty, too.
              <br />
              That's why at "Find a Loo", we're making it our business to make
              finding a place for you to do your business the less shitty thing
              of your day.
            </h3>
            <p
              style={{
                fontSize: 20,
                textAlign: "center",
                marginTop: 40,
                fontFamily: "Mulish, sans-serif",
                fontWeight: "400",
              }}
            >
              Click the button below to find a loo to do your doo, and we'll
              come through-with the nearest, free public restroom in your area.
              Because we give a shit about where you handle your shit.
            </p>
            <Link
              href={"/current-location"}
              style={{
                alignSelf: "center",
              }}
            >
              <button
                style={{
                  margin: "40px 80px",
                  padding: "20px 60px",
                  borderRadius: "25px",
                  backgroundColor: "whitesmoke",
                  color: "black",
                  fontFamily: "Mulish, sans-serif",
                  fontSize: 18,
                  fontWeight: "bolder",
                  cursor: "pointer",
                }}
              >
                Find Loo Near You
              </button>
            </Link>
          </div>
        </section>
      </main>
    </>
  );
}
